- name: Create cinder scheduler configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-scheduler
    namespace: '{{ namespace }}'
    state: present
    verify_ssl: false
    labels:
      app: cinder-scheduler
      service: cinder-scheduler
    data:
      config.json: |
        {
            "command": "cinder-scheduler --config-file /etc/cinder/cinder.conf",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        [DEFAULT]
        glance_api_servers=none
        glance_api_version=2
        enable_v3_api=True
        storage_availability_zone=nova
        default_availability_zone=nova
        auth_strategy=noauth
        enabled_backends=tripleo_iscsi
        nova_catalog_info=compute:nova:internalURL
        nova_catalog_admin_info=compute:nova:adminURL
        scheduler_driver=cinder.scheduler.filter_scheduler.FilterScheduler
        osapi_volume_listen=0.0.0.0
        osapi_volume_workers=2
        log_dir=/var/log/cinder
        transport_url=rabbit://guest:ZMCjt4emDMGppGDzevNG3zBPB@rabbitmq:5672/?ssl=0
        rpc_backend=rabbit
        control_exchange=openstack
        api_paste_config=/etc/cinder/api-paste.ini

        [database]
        connection=mysql+pymysql://cinder:cinderpass@mariadb:3306/cinder
        max_retries=-1
        db_max_retries=-1

        [oslo_concurrency]
        lock_path=/var/lib/cinder/tmp

        [oslo_messaging_notifications]
        driver=messagingv2
        transport_url=rabbit://guest:ZMCjt4emDMGppGDzevNG3zBPB@rabbitmq:5672/?ssl=0

        [oslo_messaging_rabbit]
        ssl=False
        rabbit_port=5672
        rabbit_userid=guest
        rabbit_password=ZMCjt4emDMGppGDzevNG3zBPB
        heartbeat_timeout_threshold=60

        [oslo_middleware]
        enable_proxy_headers_parsing=True

        [oslo_policy]
        policy_file=/etc/cinder/policy.json

        [tripleo_iscsi]
        volume_backend_name=tripleo_iscsi
        volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
        iscsi_ip_address=iscsid
        iscsi_helper=lioadm
        volumes_dir=/var/lib/cinder/cinder-volumes
        iscsi_protocol=iscsi

- name: create cinder-scheduler deployment
  k8s_v1beta1_deployment:
    name: cinder-scheduler
    namespace: '{{ namespace }}'
    labels:
      app: cinder-scheduler
      service: cinder-scheduler
    replicas: 1
    spec_template_metadata_labels:
      app: cinder-scheduler
      service: cinder-scheduler
    containers:
    - image: tripleoupstream/centos-binary-cinder-scheduler:latest
      name: cinder-scheduler
      env:
        - name: TZ
          value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
      volume_mounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
    volumes:
      - name: kolla-config
        config_map:
          name: cinder-scheduler

