- name: Create iscsid configmap
  ignore_errors: yes
  k8s_v1_config_map:
    name: iscsid
    namespace: '{{ namespace }}'
    state: present
    verify_ssl: false
    labels:
      app: iscsid
      service: iscsid
    data:
      config.json: |
        {
            "command": "/usr/sbin/iscsid -f",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/initiatorname.iscsi",
                    "dest": "/etc/iscsi/initiatorname.iscsi",
                    "owner": "root",
                    "perm": "0600"
                }
            ]
        }

      initiatorname.iscsi: |
        InitiatorName=iqn.1994-05.com.redhat:d84a2a2d0d1

- name: Create Iscsid Deployment
  k8s_v1beta1_deployment:
    name: iscsid
    namespace: '{{ namespace }}'
    service_account_name: openstack-priv
    node_selector:
      controller: "true"
    labels:
      app: iscsid
      service: iscsid
    replicas: 1
    spec_template_metadata_labels:
      app: iscsid
      service: iscsid
    containers:
    - name: iscsid
      image: tripleoupstream/centos-binary-iscsid:latest
      image_pull_policy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/localtime
          name: host-etc-localtime
          readOnly: true
        - mountPath: /run
          name: run
        - mountPath: /dev
          name: dev
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /var/lib/cinder
          name: cinder-volumes
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
        - name: sys-fs-cgroup
          mountPath: /sys/fs/cgroup
      env:
        - name: TZ
          value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
    volumes:
      - name: kolla-config
        config_map:
          name: iscsid
      - name: host-etc-localtime
        hostPath:
          path: /etc/localtime
      - name: cinder-volumes
        hostPath:
          path: /var/lib/cinder
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: run
        hostPath:
          path: /run
      - name: dev
        hostPath:
            path: /dev
      - name: sys-fs-cgroup
        hostPath:
          path: /sys/fs/cgroup

